name: "rust"
on: "push"
jobs:
  build:
    name: "build"

    strategy:
      fail-fast: false
      matrix:
        program: ["collision-black-box", "cli-check"]
        include:
          - os: "macos"
            runner: "macos-latest"
            target: "x86_64-apple-darwin"
            suffix: ""

          - os: "linux"
            runner: "ubuntu-latest"
            target: "x86_64-unknown-linux-musl"
            suffix: ""

          - os: "windows"
            runner: "windows-latest"
            target: "x86_64-pc-windows-msvc"
            suffix: ".exe"

    runs-on: "${{ matrix.runner }}"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: "toolchain"
        uses: "actions-rs/toolchain@v1.0.6"
        with:
          toolchain: "nightly"
          target: "${{ matrix.target }}"
          override: true

      - name: "cargo"
        uses: "actions-rs/cargo@v1.0.1"
        with:
          command: "build"
          args: "--release --manifest-path ./${{ matrix.program }}/Cargo.toml --target ${{ matrix.target }}"

      - name: "upload"
        uses: "actions/upload-artifact@v3"
        with:
          name: "build-${{ matrix.os }}"
          path: "${{ matrix.program }}/target/${{ matrix.target }}/release/${{ matrix.program }}${{ matrix.suffix }}"

  release:
    name: "release"
    runs-on: "ubuntu-latest"
    needs: "build"

    steps:
      - name: "download-macos"
        uses: "actions/download-artifact@v3"
        with:
          name: "build-macos"
          path: "macos"

      - name: "download-windows"
        uses: "actions/download-artifact@v3"
        with:
          name: "build-windows"
          path: "windows"

      - name: "download-linux"
        uses: "actions/download-artifact@v3"
        with:
          name: "build-linux"
          path: "linux"

      - name: "rename-executables"
        run: |
          mkdir -p 'release'
          for prog in 'collision-black-box' 'cli-check'; do
            mv "macos/$prog" "release/$prog-macos"
            mv "windows/$prog.exe" "release/$prog.exe"
            mv "linux/$prog" "release/$prog-linux"
          done

      - name: "release"
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest"
          files: "release/*"
