name: "rust"
on: "push"
jobs:
  main:
    name: "windows"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"
      - name: "cargo"
        uses: "actions-rs/cargo@v1.0.1"
        with:
          command: "build"
          args: "--manifest-path ./cli/Cargo.toml"
      - name: "ls"
        run: |
          ls -l cli/target
          ls -l cli/target/*
      - name: "release"
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest"
          files: ""
